hub: EMEA
environment: TEST
region: eu-central-1
profile: EMEA-TEST

prometheus:
    alertmanagerUrl: <<TODO: set correct Prometheus alert manager URL>>
    alertRules:
        - backend.yaml
    scrapeConfigs:
        - scrape-configs/backend.yaml
