groups:
  - name: backend_General_Error_During_Udp_Receive
    interval: 30s
    rules:
      - alert: backend_General_Error_During_Udp_Receive
        expr: sum(increase(application:errors_total{errorId="backend0000"}[5m])) > 30
        for: 5m
        labels:
          priority: "{{ $externalLabels.priorityLow }}"
          event_id: 80100
        annotations:
          sub_source: "{{ $labels.arn }}"
          summary: "{{ $externalLabels.priorityLow }} - General error during udp receive - HUB: {{ $externalLabels.HUB }} - Environment: {{ $externalLabels.ENV }} - Task name: {{ $labels.task_name }} - Instance: {{ $labels.instance }} - ARN: {{ $labels.arn }}"
          description: "During receiveing a upd packet from vehicle an io error occured."

  - name: backend_Error_Udp_Receive_SocketTimeout
    interval: 30s
    rules:
      - alert: backend_Error_Udp_Receive_SocketTimeout
        expr: sum(increase(application:errors_total{errorId="backend0001"}[5m])) > 30
        for: 5m
        labels:
          priority: "{{ $externalLabels.priorityLow }}"
          event_id: 80101
        annotations:
          sub_source: "{{ $labels.arn }}"
          summary: "{{ $externalLabels.priorityLow }} - UDP receive sockettimeout - HUB: {{ $externalLabels.HUB }} - Environment: {{ $externalLabels.ENV }} - Task name: {{ $labels.task_name }} - Instance: {{ $labels.instance }} - ARN: {{ $labels.arn }}"
          description: "During receiving a SocketTimeout occured which could have several reasons (e.g. vehicle offline, network problem)"

  - name: backend_Error_No_Port_Available
    interval: 30s
    rules:
      - alert: backend_Error_No_Port_Available
        expr: sum(increase(application:errors_total{errorId="backend0002"}[5m])) > 30
        for: 5m
        labels:
          priority: "{{ $externalLabels.priorityLow }}"
          event_id: 80102
        annotations:
          sub_source: "{{ $labels.arn }}"
          summary: "{{ $externalLabels.priorityLow }} - No port available - HUB: {{ $externalLabels.HUB }} - Environment: {{ $externalLabels.ENV }} - Task name: {{ $labels.task_name }} - Instance: {{ $labels.instance }} - ARN: {{ $labels.arn }}"
          description: "backend tries to bind a udp socket which wasn't possible for 3 times"

  - name: backend_Error_No_Valid_Vehicle_Response_In_Time
    interval: 30s
    rules:
      - alert: backend_Error_No_Valid_Vehicle_Response_In_Time
        expr: sum(increase(application:errors_total{errorId="backend0003"}[5m])) > 30
        for: 5m
        labels:
          priority: "{{ $externalLabels.priorityLow }}"
          event_id: 80103
        annotations:
          sub_source: "{{ $labels.arn }}"
          summary: "{{ $externalLabels.priorityLow }} - No valid vehicle response in time - HUB: {{ $externalLabels.HUB }} - Environment: {{ $externalLabels.ENV }} - Task name: {{ $labels.task_name }} - Instance: {{ $labels.instance }} - ARN: {{ $labels.arn }}"
          description: "backend listens for vehicle udp responses for a certain time. If there is no response (e.g. network problems) this error is thrown"